/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:f3373afe-335a-43a2-904a-7b37f4e71a91",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_gHZLjX0lt",
    "aws_user_pools_web_client_id": "21komflb5pb9n0picrlfj3sq3b",
    "oauth": {
        "domain": "gymii-dev.auth.us-east-1.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "https://test.com/",
        "redirectSignOut": "https://test.com/lougout/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS"
};


export default awsmobile;
